docs/dev/trace-analytics-rfc.md

*Issue #39*
* Updated the RFC to link to the github issue within our repo.
* Fixed typos.

Update the RFC Github issue

---

situp-api/src/main/java/com/amazon/situp/model/configuration/PluginSetting.java
situp-plugins/common/src/main/java/com/amazon/situp/plugins/buffer/BlockingBuffer.java

* Add helper method to PluginSettings for type specific attribute returns

Add helper methods in PluginSettings

---

situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapRelationship.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapTestUtils.java

Adding trace group resolution, and relationship cache. Updated test to test these changes.

Adding relationship cache and trace group resolution

---

situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/source/oteltrace/OTelTraceSourceTest.java

Fix the OTelTraceSoruceTest

---

situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapRelationship.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapTestUtils.java

Update servicemap processor to ExportTraceServiceRequest

---

situp-core/build.gradle
situp-plugins/build.gradle
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSinkIT.java

* Fixed the flaky integ test by using refresh API instead of sleep.
* Included all the plugins as a part of the build.

Add all plugins to the core build

---

situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/processor/oteltrace/OTelTraceRawProcessor.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapTestUtils.java

* The Raw processors was sending array list of json as the docs.
* The service-map processor was using a different key. 

Fix processors to work with our sample data

---

situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSinkIT.java

#73 
Fixes index existence check for non-raw span.

FIX: index existence check and test case

---

situp-plugins/service-map-stateful/README.md
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/OTelHelper.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapTestUtils.java

1. Get service name and store the data in LMDB only if service name is available.
2. Check if span is valid and store only valid spans.

Add valid checks to spans before writing to state store.

---

situp-core/src/main/java/com/amazon/situp/pipeline/ProcessWorker.java

Small fix to make process worker work with Stateful processor.

Remove sleep and allow empty list to processors.

---

examples/Dockerfile
examples/jaeger-hotrod/README.md
examples/jaeger-hotrod/docker-compose.yml
examples/jaeger-hotrod/otel-collector-config.yml
examples/trace_analytics.yml

Sample demo with Jaeger Hot rod app.

Add example demo with Jaeger Hot rod app

---

situp-plugins/lmdb-processor-state/src/main/java/com/amazon/situp/plugins/processor/state/LmdbProcessorState.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java

- Adding logging to ServiceMapStatefulProcessor and LmdbProcessorState
- Catching and logging errors in ServiceMapStatefulProcessor

Adding logging to service map plugin

---

situp-api/src/main/java/com/amazon/situp/model/sink/Sink.java
situp-core/src/main/java/com/amazon/situp/pipeline/Pipeline.java
situp-core/src/main/java/com/amazon/situp/pipeline/PipelineConnector.java
situp-core/src/main/java/com/amazon/situp/pipeline/ProcessWorker.java
situp-core/src/test/java/com/amazon/situp/plugins/TestSink.java
situp-plugins/common/src/main/java/com/amazon/situp/plugins/sink/FileSink.java
situp-plugins/common/src/main/java/com/amazon/situp/plugins/sink/StdOutSink.java
situp-plugins/common/src/test/java/com/amazon/situp/plugins/sink/TestSink.java
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSinkIT.java

Update the sink interface to remove Boolean return.
*Next*
* Update Pipeline Connector for Shutdown behavior

Update sink interface

---

situp-core/src/main/java/com/amazon/situp/Situp.java
situp-core/src/main/java/com/amazon/situp/parser/PipelineParser.java
situp-core/src/main/java/com/amazon/situp/pipeline/Pipeline.java
situp-core/src/main/java/com/amazon/situp/pipeline/PipelineConnector.java
situp-core/src/main/java/com/amazon/situp/pipeline/common/PipelineThreadPoolExecutor.java
situp-core/src/test/java/com/amazon/situp/pipeline/PipelineTests.java

*Issue #90*
The description of the changes is moved to Issue#90.

Exception handling in control flow

---

situp-core/src/main/java/com/amazon/situp/Situp.java
situp-core/src/main/java/com/amazon/situp/pipeline/Pipeline.java

* stopRequested to true *this was mistakenly deleted in previous PR*
* Add shutdown(pipelineName) from Situp

Start stop

---

situp-api/src/main/java/com/amazon/situp/model/configuration/PluginSetting.java
situp-core/src/main/java/com/amazon/situp/Situp.java
situp-core/src/main/java/com/amazon/situp/parser/PipelineParser.java
situp-core/src/main/resources/situp-default.yml
situp-core/src/test/java/com/amazon/situp/SitupTests.java
situp-core/src/test/java/com/amazon/situp/TestDataProvider.java
situp-core/src/test/java/com/amazon/situp/pipeline/PipelineTests.java
situp-core/src/test/java/com/amazon/situp/plugins/TestSink.java
situp-core/src/test/java/com/amazon/situp/plugins/TestSource.java
situp-core/src/test/resources/no_pipelines_to_execute.yml

* Add basic unit tests for Pipeline and Situp, will add more in subsequent PRs.
* Also update PluginSetting to avoid ClassCastException when getLong is called for int value attribute.

Add basic unit tests for Pipeline and Situp

---

examples/Dockerfile
examples/jaeger-hotrod/docker-compose.yml
examples/kibana-trace-analytics/Dockerfile
examples/situp-wait-for-odfe-and-start.sh

ENH:  add kibana trace analytics plugin and ES health check script into example setup

---

research/zipkin-elastic-to-otel/README.md
research/zipkin-elastic-to-otel/src/main/java/com/amazon/situp/research/zipkin/ElasticsearchReader.java
research/zipkin-elastic-to-otel/src/main/java/com/amazon/situp/research/zipkin/ZipkinElasticToOtel.java
research/zipkin-elastic-to-otel/src/main/java/com/amazon/situp/research/zipkin/ZipkinElasticToOtelProcessor.java
situp-core/src/main/java/com/amazon/situp/Situp.java

FIX: time conversion and add span name when importing zipkin data from elastic to otel

---

examples/jaeger-hotrod/README.md

* Updated link for Kibana trace analytics dashboard.

Update trace analytics url

---

.github/workflows/situp-e2e-tests.yml
situp-core/integrationTest.gradle

Should be reviewed after merging #88 
Add the situp-e2e-tests.yml for running integration tests in CI

ADD: e2e test github workflow

---

.dockerignore
examples/Dockerfile
examples/jaeger-hotrod/docker-compose.yml
examples/odfe-pipes-trace-app/docker-compose.yml
examples/zipkin-sleuth-webmvc-example/docker-compose.yml

FIX: mount necessary files in examples

---

situp-core/src/integrationTest/java/com/amazon/situp/integration/EndToEndRawSpanTest.java
situp-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSinkIT.java
situp-plugins/elasticsearch/src/test/resources/raw-span-1.json
situp-plugins/elasticsearch/src/test/resources/raw-span-2.json
situp-plugins/elasticsearch/src/test/resources/raw-span-error.json

ENH: update raw span index template

---

examples/jaeger-hotrod/docker-compose.yml
examples/situp/DOCKERFILE

Build the jar and use it for AppTest

---

examples/jaeger-hotrod/docker-compose.yml

Rmeove the kibana plugin.

---

examples/odfe-pipes-trace-app/docker-compose.yml
examples/odfe-pipes-trace-app/opentelemetry-collector/otel-collector-config.yml

FIX: add certificate in the situp config of sample app

---

examples/odfe-pipes-trace-app/client/client.py
examples/odfe-pipes-trace-app/client/requirements.txt
examples/odfe-pipes-trace-app/docker-compose.yml
examples/odfe-pipes-trace-app/python-services/databaseService.py
examples/odfe-pipes-trace-app/python-services/orderService.py
examples/odfe-pipes-trace-app/python-services/script.sh

- make direct mysql calls to initialize and cleanup DB.
- add orderService into sample app python service stack
- make client calls to create more traceGroup

ENH: add new trace groups

---

examples/odfe-pipes-trace-app/elastic-oss/docker-compose.yml
examples/situp-wait-for-elastic-oss.sh
examples/trace_analytics_elastic_oss.yml

@joshuali925  requested a elastic OSS version of docker compose so he could test it locally. 

Add Elastic OSS docker-compose

---

examples/odfe-pipes-trace-app/elastic-oss/docker-compose.yml

FIX: sync docker-compose on elastic-oss

---

situp-core/src/main/java/com/amazon/situp/parser/PipelineParser.java
situp-core/src/main/java/com/amazon/situp/parser/model/PipelineConfiguration.java
situp-core/src/test/java/com/amazon/situp/TestDataProvider.java
situp-core/src/test/java/com/amazon/situp/parser/model/PipelineConfigurationTests.java
situp-plugins/common/src/main/java/com/amazon/situp/plugins/buffer/BlockingBuffer.java

The PR includes changes to move the Defaults to PipelineConfiguration as suggested in previous #128 

Restructure defatults

---

situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ConnectionConfiguration.java

```
sink:
- elasticsearch:
hosts: [ "https://localhost:9200" ]
insecure: true
username: "admin"
password: "admin"
trace_analytics_raw: true
```
NOTE: This is in a separate branch.

Add new insecure flag to elasticsearch sink

---

examples/kibana-trace-analytics/Dockerfile

Use the latest kibana plugin which uses the latest model and supports service-map,

Use the latest kibana plugin.

---

examples/odfe-pipes-trace-app/python-services/databaseService.py
examples/odfe-pipes-trace-app/python-services/inventoryService.py
examples/odfe-pipes-trace-app/python-services/orderService.py
examples/odfe-pipes-trace-app/python-services/paymentService.py

ENH: introduce error in checkout and remove unused get headers

---

examples/odfe-pipes-trace-app/client/client.py
examples/trace_analytics.yml
examples/trace_analytics_elastic_oss.yml
examples/trace_analytics_no_ssl.yml

Use the sleep time in the client app.

---

examples/adot/docker-compose.yml
examples/jaeger-hotrod/docker-compose.yml
examples/jaeger-hotrod/otel-collector-config.yml
examples/odfe-pipes-trace-app/docker-compose.yml
examples/zipkin-sleuth-webmvc-example/docker-compose.yml

[Side Branch] Otel collectorv0.14.0

---

examples/odfe-pipes-trace-app/analytics-service/Dockerfile
examples/odfe-pipes-trace-app/analytics-service/src/main/java/com/example/restservice/LoggingController.java

Update javaagent to latest and introduce random error in /logs

---

build.gradle

Drop beta from version

---

situp-plugins/common/README.md

ADD: readme for situp-plugin commons

---

release/build.gradle
release/docker/data-prepper-v0.1.0-all.Dockerfile
research/zipkin-elastic-to-otel/build.gradle

* Update the Dockerfile content (which was missed in previous PR)
* Update research project execute file in build.gradle
* Update comments in release/build.gradle
```
simple-ingest-transformation-utility-pipeline byadav$ ./gradlew -Prelease :release:docker:docker
Starting a Gradle Daemon, 19 busy and 72 incompatible Daemons could not be reused, use --status for details
=======================================
Elasticsearch Build Hamster says Hello!
Gradle Version        : 6.5
OS Info               : Mac OS X 10.14.6 (x86_64)
JDK Version           : 14 (Oracle JDK)
JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
Random Testing Seed   : E7A1190F8797514
In FIPS 140 mode      : false …
```

Rename Dockerfile content

---

examples/Dockerfile
examples/adot/docker-compose.yml
examples/data-prepper-wait-for-odfe-and-start.sh
examples/jaeger-hotrod/README.md
examples/jaeger-hotrod/docker-compose.yml
examples/trace-analytics-sample-app/README.md
examples/trace-analytics-sample-app/docker-compose.yml
examples/zipkin-sleuth-webmvc-example/docker-compose.yml
release/build.gradle

* Change the yml file name from transformation instance to trace analytics.
* Fix outdated readme.
*Testing*
Ran the sample app locally and tested it. 

Update example config file name and readme

---

release/release-notes/odfe-data-prepper.release-notes-0.1.0.md

Add release notes for v0.1.0

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/resources/connected_pipeline_incorrect_child_pipeline.yml
data-prepper-core/src/test/resources/connected_pipeline_incorrect_root_source.yml

This was reviewed and approved as part of #195 

Fix logging and pipeline failure during init

---

build.gradle

Alpha version

---

build.gradle

Pushing the commits from v0.7.x branch to master for version update

Merge from v0.7.x to master for version change

---

data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarder.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderTest.java

Contributes to #200 
Manifested inline.

MAINT: make PeerForwarder extends metric compatible abstract class

---

docs/readme/overview.md

Update the heading of the Overiew.

Change Overview heading

---

data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/DiscoveryMode.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/DnsPeerListProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProviderFactory.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/StaticPeerListProvider.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderConfigTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/DnsPeerListProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProviderFactoryTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/StaticPeerListProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

*Issue #, if available:* #200
* Added DNS implementation and updated factory
* Updated Readme

#200: Added DNS PeerListProvider implementation.

---

THIRD-PARTY
release/archives/build.gradle
release/docker/data-prepper-v0.1.0-all.Dockerfile

* Replace adoptopenjdk/alpine with amazoncorreto:15-al2-full
* Include `THIRD-PARTY` attributions

Switch DockerFile to AmazonCorretto. Add THIRD-PARTY attributions.

---

THIRD-PARTY

Give attribution to all the projects that are part of our final uber jar.

Update with more attribution.

---

build.gradle
data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/otel-trace-raw-processor/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle

*Issue #, if available:* #239
Bringing up the jacoco plugin to the top level so that all projects will have access to coverage reports. Will eventually enable enforcement, but we need to establish baselines first.

Applied the jacoco code coverage gradle plugin to all subprojects.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/test/java/com/amazon/dataprepper/metrics/PluginMetricsTest.java

MNT: name on gauge in PluginMetrics

---

examples/dev/README.md
examples/dev/dns/Dockerfile
examples/dev/dns/dnsmasq.conf
examples/dev/dns/hosts.prepper
examples/dev/trace-analytics-sample-app/Dockerfile
examples/dev/trace-analytics-sample-app/README.md
examples/dev/trace-analytics-sample-app/docker-compose.yml
examples/dev/trace-analytics-sample-app/opentelemetry-collector/otel-collector-config.yml
examples/dev/trace-analytics-sample-app/resources/data-prepper-wait-for-odfe-and-start.sh
examples/dev/trace-analytics-sample-app/resources/trace_analytics_no_ssl.yml

* Created a /dev directory to test local changes with docker-compose. 
* Recreated the trace sample app example and added a DNS container.
Plan is to use this as a staging area to test changes, then eventually move those changes to the supported, non-dev examples/ directory. 

Added examples/dev directory to test local changes using Docker.

---

examples/dev/trace-analytics-sample-app/README.md
examples/dev/trace-analytics-sample-app/docker-compose.yml
examples/dev/trace-analytics-sample-app/prometheus/prometheus.yaml

* Added Prometheus and Grafana containers to dev docker-compose project
* Updated readme with instructions on how to access metrics and visualizations

Added Prometheus and Grafana containers to dev docker-compose project.

---

README.md
docs/readme/logs.md
docs/readme/monitoring.md
docs/readme/project_setup.md

- Adding documentation for project setup, logging, and monitoring
- Because this is the README of the source, documentation is geared towards people building from source or contributing, rather than end users

Adding documentation for project setup, logging, and monitoring

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineConfigurationValidator.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/common/FutureHelper.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/PipelineConnectorTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/PipelineTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/common/FutureHelperResultTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/common/FutureHelperTest.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/common/PipelineThreadPoolExecutorTest.java

*Issue #, if available:* #239
* Added unit tests to improve coverage (now 85% line and 74% branch)
* Added TODO cleanup comments to 2 seemingly unused methods

#239: Added misc unit tests to data-prepper-core classes.

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/common/PipelineThreadPoolExecutor.java

Increased code coverage threshold for data-prepper-core project to match recent changes.

Increased code coverage threshold for data-prepper-core project.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/MetricNames.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/PluginType.java
data-prepper-api/src/main/java/com/amazon/dataprepper/processor/state/PrepperState.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/PluginTypeTests.java
data-prepper-benchmarks/lmdb-benchmarks/src/jmh/java/com/amazon/dataprepper/benchmarks/processor/state/LmdbPrepperStateBenchmarks.java
data-prepper-benchmarks/mapdb-benchmarks/src/jmh/java/com/amazon/dataprepper/benchmarks/processor/state/MapDbPrepperStateBenchmarks.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/PipelineConfiguration.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/PipelineConfigurationTests.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/PluginRepository.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/processor/NoOpPrepper.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/processor/PrepperFactory.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/processor/StringPrepper.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/processor/PrepperFactoryTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/processor/state/PrepperStateTest.java
data-prepper-plugins/lmdb-processor-state/src/main/java/com/amazon/dataprepper/plugins/processor/state/LmdbPrepperState.java
data-prepper-plugins/lmdb-processor-state/src/test/java/com/amazon/dataprepper/plugins/processor/state/LmdbPrepperStateTest.java
data-prepper-plugins/mapdb-processor-state/src/main/java/com/amazon/dataprepper/plugins/processor/state/MapDbPrepperState.java
data-prepper-plugins/mapdb-processor-state/src/test/java/com/amazon/dataprepper/plugins/processor/state/MapDbPrepperStateTest.java
data-prepper-plugins/otel-trace-raw-processor/src/main/java/com/amazon/dataprepper/plugins/processor/oteltrace/OTelTraceRawPrepper.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarder.java
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/processor/ServiceMapStatefulPrepper.java
research/zipkin-elastic-to-otel/src/main/java/com/amazon/dataprepper/research/zipkin/ZipkinElasticToOtel.java
research/zipkin-elastic-to-otel/src/main/java/com/amazon/dataprepper/research/zipkin/ZipkinElasticToOtelPrepper.java

*Issue #, if available:* #209
* Renaming classes/variables
* Will rename directories in follow-up PR

Second pass of renaming 'processor' to 'prepper'.

---

data-prepper-plugins/common/build.gradle
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/PluginRepository.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/StringPrepper.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/sink/FileSink.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/StringPrepperTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/FileSinkTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/sink/StdOutSinkTests.java

#239 
- increase test coverage on common plugins
- raise the enforcement to 90%
- delete unused API

ENH: increase coverage on common plugins

---

data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java
data-prepper-plugins/otel-trace-source/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

#239 
- Add more test cases on OtelTraceSource and OtelTraceSourceConfig
- Enforce 90% coverage

ENH: increase test coverage on otel trace source

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

Added support for ES domains in VPCs to the CloudFormation script. Tested against public and VPC ES domains.

Added support for ES domains in VPCs to the CloudFormation script.

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

* Artifact location changed, updating the CFN script to match

Minor fix in CFN script to release artifacts download path.

---

deployment/aws/ec2/data-prepper-ec2-deployment-cfn.yaml

*Issue #304*
* Added the heap as a parameter and set it as JAVA_OPTS.
* Use same workers, buffer and batch size.

Add jvm heap as a cfn parameter.

---

deployment/aws/ec2/data-prepper-ec2-deployment-cfn.yaml

* The append was missing and the signal never happened, so cfn applies rollback. 

Fix the nohup append.

---

data-prepper-plugins/elasticsearch/security.md
deployment/aws/ec2/data-prepper-ec2-deployment-cfn.yaml

* Service-Map has an issue with parallelism (suspect a race condition), so changed the cfn to use default 1 worker, this is might impact the scale test.  Issue: #320 
* Made copy-pasta error and missed the `_bulk` permissions.

Remove ServiceMap worker and Add _bulk in permissions.

---

data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

*Issue #, if available:* #221
* Changing `BlockingBuffer` variable in unit test from static to instance
Potentially fixing the flaky testBufferFull() test (though I'm not 100% sure as it's tough to reproduce). Noticed the buffer object isn't being re-initialized between each test, so maybe the buffer is already full by the time this particular test is reached?

221: Removing unnecessary static keyword in OTelTraceSource test class.

---

README.md
docs/readme/trace_setup.md
docs/readme/trace_tuning.md

Add scaling and tuning readme.

---

data-prepper-plugins/service-map-stateful/README.md
docs/readme/trace_setup.md
docs/readme/trace_tuning.md

Updated the scaling read me with guidelines. 

Update scaling readme.

---

deployment/aws/ec2/data-prepper-ec2-deployment-cfn.yaml
docs/readme/trace_tuning.md

Changed variable names in CFN template.

---

data-prepper-plugins/elasticsearch/security.md

#338 
Tested with examples/dev/trace-analytics-sample-app.
Note: For now there is lack of permissions to ISM control. So I need to assign cluster_all and allow all access to .opendistro-ism-config.

DOC: permissions needed for ES sink applied to ODFE

---

data-prepper-plugins/elasticsearch/odfe_security.md
data-prepper-plugins/elasticsearch/security.md

Pulled from v0.7.x and minor changes

ES sink security doc for ODFE and AES

---

data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java

Added misc logging in Otel Source.

---

data-prepper-core/integrationTest.gradle
research/zipkin-elastic-to-otel/build.gradle

* Upgrading more dependencies. 

Upgrading dependencies.

---

.github/workflows/data-prepper-trace-analytics-e2e-tests.yml
CONTRIBUTING.md
data-prepper-plugins/blocking-buffer/README.md
data-prepper-plugins/elasticsearch/README.md
data-prepper-plugins/otel-trace-raw-prepper/README.md
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/service-map-stateful/README.md

Issue: #399
* Updating docs and links

Renaming master branch to main.

---

build.gradle

* Minor version bump of log4j-core
-----
person who certified (a), (b) or (c) and …

Updated log4j-core version.

---

deployment-template/ec2/README.md
deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml
deployment-template/eks/README.md
deployment-template/eks/ingress.yaml
deployment-template/k8s/README.md
deployment-template/k8s/data-prepper-k8s.yaml
deployment-template/k8s/data-prepper.yaml

* Added EKS and k8s deployment files.
-----
person who certified (a), (b) or (c) …

Added EKS and k8s deployment files.

---

data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle

* Increasing micrometer version now that fix should be out.
-----
person who …

Upgrading micrometer version.

---

THIRD-PARTY
release/docker/opendistroforelasticsearch-data-prepper-0.7.1-alpha.Dockerfile

* Updated attributions
-----
person who certified (a), (b) or (c) and I have not …

Updated THIRD-PARTY attributions.

---

deployment-template/eks/README.md
release/release-notes/odfe-data-prepper.release-notes-0.7.0.md
release/release-notes/odfe-data-prepper.release-notes-0.8.0.md

* Added release notes for v0.8.0.
-----
person who certified (a), (b) or (c) and …

Added release notes for v0.8.0.

---

docs/readme/trace_tuning.md

* Minor update to scaling docs.
* Still need to get actual scaling values  (currently being worked on)
-----
(c) The contribution was provided …

Minor update to scaling docs.

---

build-resources.gradle
data-prepper-plugins/peer-forwarder/build.gradle
examples/dev/trace-analytics-sample-app/docker-compose.yml
examples/trace-analytics-sample-app/docker-compose.yml
examples/trace-analytics-sample-app/sample-app/Dockerfile
examples/trace-analytics-sample-app/sample-app/analytics-service/Dockerfile
examples/trace-analytics-sample-app/sample-app/authenticationService.py
examples/trace-analytics-sample-app/sample-app/client.py
examples/trace-analytics-sample-app/sample-app/databaseService.py
examples/trace-analytics-sample-app/sample-app/inventoryService.py
examples/trace-analytics-sample-app/sample-app/orderService.py
examples/trace-analytics-sample-app/sample-app/paymentService.py
examples/trace-analytics-sample-app/sample-app/recommendationService.py
examples/trace-analytics-sample-app/sample-app/requirements.txt

*Issue #, if available:* #435
* Upgraded dependencies now that OTel Proto has reached the 1.0 release
* Tested with /dev sample app and non-/dev sample app
-----
permitted to submit under a different license), as …

Upgraded OpenTelemetry dependencies.

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

* Found an issue with the CFN template with 0.8.x incompatible changes. Missed testing the CFN template before release.
* Tested by deploying and tailing the log file, no startup errors.
-----
permitted to submit under a …

Fixed CFN template to be compatible with v0.8.x changes.

---

data-prepper-plugins/otel-trace-group-prepper/README.md
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-group-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltracegroup/OTelTraceGroupPrepper.java
data-prepper-plugins/otel-trace-group-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/oteltracegroup/OTelTraceGroupPrepperTests.java

-----
person who certified (a), (b) or (c) and I have …

ENH: introduce spans missing trace group counter

---

data-prepper-plugins/elasticsearch/security.md

Custom endpoint will work as long as the certificates are passed. 
-----
person who certified (a), (b) or …

Custom endpoint is no longer a limitation.

---

data-prepper-plugins/elasticsearch/build.gradle

Minor dependency version resolution.

---

THIRD-PARTY

* Updating attribution file
-----

Updating THIRD-PARTY attributions.

---

build.gradle

MAINT: bump version

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

#490 
-----
This PR modifies the data-prepper CloudFormation template as follows:
(1) Regroup paramters for clarity in UI
(2) Add Username and Password paramters to support HTTP basic authetication based FGAC
(3) Make IAMRole optional

MAINT: update cfn template

---

data-prepper-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/model/RawSpan.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/model/TraceGroup.java
data-prepper-plugins/otel-trace-raw-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepperTest.java

Applying backwards compatibility commit to v1.0.x branch
-----

MAINT: restore traceGroup backward compatibility (#564)

---

release/release-notes/odfe-data-prepper.release-notes-1.0.0.md

Added release notes md file.
-----

Added 1.0.0 release notes.

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

MAINT: update CFN to v1.0.x

---

build.gradle

Signed-off-by: Bala Yadav <byadav@amazon.com>
updating version to match latest tag
-----

Update version to match latest release

---

docs/readme/project_setup.md

*Issue #, if available:* None
I updated the Project Setup documentation based on some of the difficulties I had when running it. Hopefully this will make it easier to get up and running.
-----

Updated the Project Setup documentation to include JDK/build info

---

data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/certificate/acm/ACMCertificateProvider.java

* Minor update to ACMCertificateProvider.
-----

Minor update to ACMCertificateProvider.

---

data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPool.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarder.java

Update to PeerClientPool client builder.

---

data-prepper-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json
data-prepper-plugins/geoip-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/geoip/GeoIpPrepper.java
data-prepper-plugins/geoip-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/geoip/GeoIpPrepperConfig.java
data-prepper-plugins/geoip-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/geoip/provider/GeoIpProviderFactory.java
data-prepper-plugins/geoip-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/geoip/provider/LocationData.java
data-prepper-plugins/geoip-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/geoip/GeoIpPrepperTest.java
data-prepper-plugins/geoip-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/geoip/provider/GeoIpProviderFactoryTest.java

Signed-off-by: Jonah Calvo <caljonah@amazon.com>
Index template now correctly creates geo_point mapping for location
desired_fields now works properly
-----

Clean-up index template, fix desired_fields

---

release/release-notes/odfe-data-prepper.release-notes-1.1.0.md

* Added v1.1.0 release notes.
-----

Added v1.1.0 release notes.

---

build.gradle
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle

#877 
This change updates several dependency versions to newer versions which fix known CVEs.
-----

Dependency updates

---

gradle.properties

N/A
Update to Data Prepper 1.1.0
-----

Data Prepper v1.1.0

---

build.gradle

Updated Data Prepper to version 1.0.1
-----

Update to Data Prepper 1.0.1

---

release/release-notes/odfe-data-prepper.release-notes-1.0.1.md

Release notes for ODFE Data Prepper v1.0.1
-----

Release notes for ODFE Data Prepper 1.0.1

---

build.gradle
release/release-notes/odfe-data-prepper.release-notes-1.0.2.md

*Issue #, if available:* N/A
* Version bump to 1.0.2
* Added release notes for 1.0.2
-----

Preparation for Data Prepper 1.0.2.

---

build.gradle

1.0.3 version bump
