opendistro-for-elasticsearch/data-prepper

situp-plugins/elasticsearch/README.md
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSinkConfiguration.java
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/IndexConfiguration.java
situp-plugins/elasticsearch/src/main/resources/otel-v1-apm-service-map-index-template.json
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSinkIT.java
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/IndexConfigurationTests.java
situp-plugins/elasticsearch/src/test/resources/service-map-1.json

This PR
1. Update service map index template
2. Extracts `hashId` as docId in service map data
3. Fixed index patterns for service map
4. Update README about service map config and custom data config
5. Added test coverage on service map
Note:
Instead of supporting two flags `trace.analytics.raw` and `trace.analytics.servicemap`, I used `index_type` that has 3 values: `raw`, `service_map`, `custom` which I think is more compact and simplifies the logic. I can return to the double flags if it leads to a better UX.

ENH: ES sink service map integration

---

situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapRelationship.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java

- Updating target and destination of ServiceMapRelationship to be Endpoint objects (with a resource and domain)
- Updating cache to check against actual object to avoid collisions with Integer hash code
- Adding hashId field to ServiceMapRelationship, which is an Md5 hash of all of the values for the object
Decided to use Md5 hash for document id because the 4 bytes for the integer hash code could lead to potential collisions when we get into the hundreds:
https://preshing.com/20110504/hash-collision-probabilities/

Adding hash id for relationships

---

situp-plugins/apmtracesource/README.md
situp-plugins/apmtracesource/build.gradle
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceGrpcService.java
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceSource.java
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceSourceConfig.java
situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/source/oteltrace/OTelTraceSourceTest.java

*Issue #55 *
* Create a new Source plugin called ```otel_trace_source```
* This source is based of the new framework called [Armeria](https://github.com/line/armeria). This uses the OTLP protocol and supports OTLP/gRPC, OTLP/HTTP (protobuf) and OTLP/HTTP+JSON (partially).

Add OTel Trace Source

---

situp-plugins/service-map-stateful/README.md
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapProcessorConfig.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java

* Added the plugin annotation and must have pluginsetting based constructor.
* Use processorsCreated instead of number of processors config.
* Default the LMDB path

Update the service-map processor with config.

---

situp-core/src/main/java/com/amazon/situp/parser/model/PipelineConfiguration.java
situp-core/src/test/java/com/amazon/situp/TestDataProvider.java
situp-core/src/test/java/com/amazon/situp/parser/PipelineParserTests.java
situp-core/src/test/java/com/amazon/situp/parser/model/PipelineConfigurationTests.java
situp-core/src/test/resources/cyclic_multiple_pipeline_configuration.yml
situp-core/src/test/resources/incorrect_source_multiple_pipeline_configuration.yml
situp-core/src/test/resources/missing_name_multiple_pipeline_configuration.yml
situp-core/src/test/resources/missing_pipeline_multiple_pipeline_configuration.yml
situp-core/src/test/resources/valid_multiple_pipeline_configuration.yml
situp-core/src/test/resources/valid_multiple_processors.yml
situp-core/src/test/resources/valid_multiple_sinks.yml

*Issue #47 *
Made the PipelineConfiguration object strict to support. 
* Only one non-null **source**
* Only one optional **buffer**
* Zero or more optional **processors**
* One or more **sinks**

Support multiple sinks and multiple processors

---

settings.gradle
situp-api/src/main/java/com/amazon/situp/processor/state/ProcessorState.java
situp-plugins/common/src/test/java/com/amazon/situp/plugins/processor/state/ProcessorStateTest.java
situp-plugins/lmdb-processor-state/src/main/java/com/amazon/situp/plugins/processor/state/LmdbProcessorState.java
situp-plugins/mapdb-processor-state/build.gradle
situp-plugins/mapdb-processor-state/src/main/java/com/amazon/situp/plugins/processor/state/MapDbProcessorState.java
situp-plugins/mapdb-processor-state/src/test/java/com/amazon/situp/plugins/processor/state/MapDbProcessorStateTest.java
situp-plugins/service-map-stateful/build.gradle
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java

- Adding MapDB processor state plugin
- Using this plugin in the service map stateful processor
- Adding new, more generic, interface method for iterating over segments in processor state

Adding MapDB processor state and using it in Service Map Stateful Processor

---

settings.gradle
situp-benchmarks/lmdb-benchmarks/build.gradle
situp-benchmarks/lmdb-benchmarks/src/jmh/java/com/amazon/situp/benchmarks/processor/state/LmdbProcessorStateBenchmarks.java
situp-benchmarks/service-map-stateful-benchmarks/build.gradle
situp-benchmarks/service-map-stateful-benchmarks/src/jmh/java/com/amazon/situp/benchmarks/processor/ServiceMapStatefulProcessorBenchmarks.java
situp-plugins/lmdb-processor-state/src/main/java/com/amazon/situp/plugins/processor/state/LmdbProcessorState.java
situp-plugins/lmdb-processor-state/src/test/java/com/amazon/situp/plugins/processor/state/LmdbProcessorStateTest.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java

- Adding lmdb putAll method, unit test for that method, and benchmark in the same fashion as MapDB
- Adding service map stateful benchmarks
- Had to make constructor public for service map stateful processor
- Data is generated to produce edges every iteration. Tested by printing edges after every iteration (but removed for the commit)

Adding LMDB and ServiceMapStateful benchmarks

---

situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/IndexConfiguration.java
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/IndexStateManagement.java
situp-plugins/elasticsearch/src/main/resources/otel-v1-apm-service-map-index-template.json
situp-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json
situp-plugins/elasticsearch/src/test/java/com/amazon/situp/plugins/sink/elasticsearch/IndexConfigurationTests.java
situp-plugins/elasticsearch/src/test/resources/test-template-withshards.json

* Added new configuration parameters for number_of_shards and number_of_replicas. This configuration is secondary to index template setting.
Note: Skipping the README, working on coming up with a similar template for all our plugins. 

Include number_of_shards and number_of_replicas.

---

situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceSource.java
situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/source/oteltrace/OTelTraceSourceTest.java

* Update the OpenTelemetryTraceSource to throw the exceptions. As per the pipeline control flow, pipeline will stop if the source encounters issue at start.
Note:
* No testcase for stop because Aremeria framework handles the STOP very graciously. 

Throw the exceptions encountered during the start and stop of source.

---

examples/jaeger-hotrod/docker-compose.yml
examples/odfe-pipes-trace-app/docker-compose.yml
examples/zipkin-sleuth-webmvc-example/docker-compose.yml

For unknown reasons, the OTLP exporter with secure cert file doesnt work on versions after OpenTelemetry collector-0.11.0. So switching our examples to 0.11.0 while I investigate why latest versions fail.

Use OpenTelemetry Collector 0.11.0 to make source TLS work.

---

situp-core/build.gradle

Remove integration test as App test folks complained of it in their demo run.
```
sttachic@uac891278038952:~/Documents/avp3442_situp/simple-ingest-transformation-utility-pipeline/examples/jaeger-hotrod$ sudo docker-compose up -d --build
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating network "jaeger-hotrod_my_network" with the default driver
Pulling otel-collector (otel/opentelemetry-collector:0.11.0)...
0.11.0: Pulling from otel/opentelemetry-collector
aec9c7fd0082: Pull complete
73bb920a22a2: Pull complete
710006bb55f4: Pull complete
Digest: sha256:4905ac9b2acffcd3181151c8e1545864ca783f8e5761b4b8505361039a6276f3
Status: Downloaded newer image for otel/opentelemetry-collector:0.11.0
Building situp
Step 1/10 : FROM gradle:jdk14 AS builder
jdk14: Pulling from …
```

Remove integration build that is affecting the app test.

---

release/README.md
release/build-resources.gradle
release/linux/build.gradle
release/linux/situp-tar-install-with-jdk.sh
release/linux/situp-tar-install.sh
release/macOS/build.gradle
release/macOS/situp-tar-install-with-jdk.sh
release/macOS/situp-tar-install.sh
settings.gradle

* Add macOS module for mac OS compatible tar generation
* With JDK - *Notice it is using openjdk 15*
```
f45c89b92765:Temp byadav$ ./situp-macOS_x64-jdk-0.1-beta/situp-tar-install.sh situp.yml
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
0    [main] INFO  com.amazon.situp.Situp  – Using situp.yml configuration file
462  [main] INFO  com.amazon.situp.parser.PipelineParser  – Building pipeline [entry-pipeline] from provided configuration
462  [main] INFO  com.amazon.situp.parser.PipelineParser  – Building [otel_trace_source] as source component for the pipeline [entry-pipeline]
650  [main] INFO  org.reflections.Reflections  – Reflections took 159 …
```

Add mac os for tar distribution

---

situp-core/src/integrationTest/java/com/amazon/situp/integration/EndToEndRawSpanTest.java
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/processor/oteltrace/model/OTelProtoHelper.java
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/processor/oteltrace/model/RawSpan.java
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/processor/oteltrace/model/RawSpanBuilder.java
situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/processor/oteltrace/model/OTelProtoHelperTest.java
situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/processor/oteltrace/model/RawBuilderTest.java
situp-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json

Kibana team requested to add the traceGroup as a field, this would benefit the trace analytics UI. Trace Group is concept introduced by Trace Analytics UI, we call the name of the span which has no parentSpan as traceGroup.
* Added `traceGroup` to raw span
* Added field to index template and updated the E2E

Add traceGroup to the raw-index.

---

situp-core/src/integrationTest/java/com/amazon/situp/integration/EndToEndServiceMapTest.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapRelationship.java

Looks like we have bad setter issue in the ServiceMapRelationship. This was found out when I was reviewing it with @joshuali925 . 
[Original Issue.](https://github.com/opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline/issues/44)

Fix the Endpoint setter bug in ServiceMapRelationship.

---

situp-api/src/main/java/com/amazon/situp/model/configuration/PluginSetting.java
situp-api/src/test/java/com/amazon/situp/model/configuration/PluginSettingsTest.java
situp-core/src/main/java/com/amazon/situp/parser/PipelineParser.java
situp-core/src/main/java/com/amazon/situp/parser/model/PipelineConfiguration.java
situp-core/src/main/java/com/amazon/situp/pipeline/Pipeline.java
situp-core/src/test/java/com/amazon/situp/pipeline/PipelineTests.java
situp-plugins/common/src/main/java/com/amazon/situp/plugins/buffer/BlockingBuffer.java
situp-plugins/common/src/test/java/com/amazon/situp/plugins/buffer/BlockingBufferTest.java
situp-plugins/common/src/test/java/com/amazon/situp/plugins/buffer/BufferFactoryTests.java
situp-plugins/mapdb-processor-state/src/main/java/com/amazon/situp/plugins/processor/state/MapDbProcessorState.java
situp-plugins/mapdb-processor-state/src/test/java/com/amazon/situp/plugins/processor/state/MapDbProcessorStateTest.java
situp-plugins/service-map-stateful/src/main/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessor.java
situp-plugins/service-map-stateful/src/test/java/com/amazon/situp/plugins/processor/ServiceMapStatefulProcessorTest.java

#119 
1. Add pipeline level configuration like pipeline name and process workers to Plugin settings. Adding it to PluginSettings will make it available to plugins and facilitates use-cases where plugins need information about number of process workers the pipeline is running.
2. Update ServiceMapProcessor and related State class to use the process workers from PluginSettings. 

Add pipeline level configuration to PluginSettings

---

situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceSource.java

Enable ProtoReflection to allow grpcurl for AppTest.

Enable Protoreflection for App Test

---

situp-core/src/main/java/com/amazon/situp/pipeline/common/FutureHelper.java
situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ConnectionConfiguration.java

Changing future.isDone() check with call to future.get(), which will wait on results.

Using Future.get() to wait on futures in FutureHelper

---

examples/Dockerfile
examples/odfe-pipes-trace-app/docker-compose.yml
examples/situp-wait-for-odfe-and-start.sh

- Fixed xms and xmx to 128m.
- Set sleep time to 1s
Tested on `jaeger-hotrod` and `odfe-pipes-trace-app`

ENH: set min and max heap size of situp in examples

---

dependency-versions.gradle
examples/odfe-pipes-trace-app/python-services/requirements.txt
situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/processor/oteltrace/model/OTelProtoHelperTest.java
situp-plugins/apmtracesource/src/test/java/com/amazon/situp/plugins/processor/oteltrace/model/RawBuilderTest.java

#151 
- Upgraded proto dependency to v.10.0 and fixes the relevant test cases
- Upgrade on opentelemetry-python sdk to the latest working version 0.14b0
Tested with sample app, adot and jaeger. Status code now only 3 values
Note: For opentelemetry-python 0.15b0, I met with this bug https://github.com/open-telemetry/opentelemetry-python/pull/1101#discussion_r515398299

Upgrade proto to 0.10.0

---

release/archives/build.gradle
release/archives/linux/build.gradle
release/archives/macOS/build.gradle
release/build-resources.gradle

* Move common tasks to subprojects closure 
* Add zip's - _when we add windows, we will disable tar for windows_
* Update upload tasks
Next: Find a way to move the uploadArchives to parent project from subprojects.
All archives and their directories
```
byadav$ ls
situp-linux_x86_64-0.1-beta		situp-linux_x86_64-jdk-0.1-beta		situp-macOS_x64-0.1-beta		situp-macOS_x64-jdk-0.1-beta
situp-linux_x86_64-0.1-beta.tar.gz	situp-linux_x86_64-jdk-0.1-beta.tar.gz	situp-macOS_x64-0.1-beta.tar.gz		situp-macOS_x64-jdk-0.1-beta.tar.gz
situp-linux_x86_64-0.1-beta.zip		situp-linux_x86_64-jdk-0.1-beta.zip	situp-macOS_x64-0.1-beta.zip		situp-macOS_x64-jdk-0.1-beta.zip
f45c89b92765:todelete byadav$ cd situp-linux_x86_64-0.1-beta …
```

Refactor archives build.gradle

---

situp-plugins/apmtracesource/README.md
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceSource.java
situp-plugins/apmtracesource/src/main/java/com/amazon/situp/plugins/source/oteltracesource/OTelTraceSourceConfig.java

*Issue #, if available:* #160 
Adding a flag for server reflection, to allow for debugging/testing with gRPC tools such as [gprcurl](https://github.com/fullstorydev/grpcurl) and [evans](https://github.com/ktr0731/evans).
With both `health_check_service: true` and `proto_reflection_service: true`:
```
[/home/wrijeff/testing] ./grpcurl -plaintext 127.0.0.1:21890 grpc.health.v1.Health/Check
{
"status": "SERVING"
}
```

Added config flag to enable gRPC server reflection.

---

situp-plugins/elasticsearch/src/main/resources/raw-span-policy.json

50K document is really low from query perspective for spans so we decided to remove the count from the policy. We can look into this in the future if scale comes as bottleneck.

Remove the doc count from the default policy

---

examples/odfe-pipes-trace-app/analytics-service/Dockerfile
examples/odfe-pipes-trace-app/docker-compose.yml

* The flags have changed in v0.10.1, this was causing the failures. 

Upgrade to java agent v0.10.1

---

situp-api/src/main/java/com/amazon/situp/model/buffer/AbstractBuffer.java
situp-api/src/main/java/com/amazon/situp/model/metrics/MetricNames.java
situp-api/src/main/java/com/amazon/situp/model/sink/AbstractSink.java
situp-api/src/test/java/com/amazon/situp/model/buffer/AbstractBufferTest.java
situp-api/src/test/java/com/amazon/situp/model/metrics/MetricsTestUtil.java
situp-api/src/test/java/com/amazon/situp/model/processor/AbstractPrepperTest.java
situp-api/src/test/java/com/amazon/situp/model/sink/AbstractSinkTest.java

Adding Abstract implementations of Buffer and Sink for testing.
Note: The checked exception in Buffer.write() required a little bit of extra code to handle in the abstract class. The other method for doing this would be to time the method, and use the Timer.record(Duration duration) to record the time. Both implementations required a little extra code, so I did not see a huge difference between the two.

Adding abstract implementations of Sink and Buffer

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/resources/connected_pipeline_incorrect_child_pipeline.yml
data-prepper-core/src/test/resources/connected_pipeline_incorrect_root_source.yml

The changes will fail building of connected child pipelines if the connected root pipeline failed. Below is the pictorial representation of what the flow does
```
--> childPipeline1
/
rootPipeline ---
\
--> childPipeline2
```
Case: `rootPipeline` building fails for any reason
Result: It skips `rootPipeline` and proceeds building of `childPipeline1` (or `childPipeline2`) -> As part of building source where it requires a `PipelineConnector` (connector to `rootPipeline`) and attempts to retrieve from `sourceConnectorMap` but as r`ootPipeline` failed, there will not be any `PipelineConnector`. It assumes the `rootPipeline` building hasn't started and attempts to build and checks if the `Pipeline` was created, failing to find a `Pipeline` - It …

Fail creation of connected pipelines if root pipeline fails

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/PipelineParserTests.java
data-prepper-core/src/test/resources/connected_pipeline_incorrect_child_pipeline.yml
data-prepper-core/src/test/resources/connected_pipeline_incorrect_root_source.yml

Cherry-pick commit of the [fix](https://github.com/opendistro-for-elasticsearch/Data-Prepper/pull/197) applied on the release. 

Fix logging and pipeline failure during init

---

data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/HashRing.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarder.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/HashRingTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderTest.java

Contributes to #200 
Replace consistent hashing algorithm of IP address and traceId in Peerforwarder with HashRing.

Use HashRing in Peerforwarder

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/PrometheusMetricsHandler.java
data-prepper-core/src/test/java/com/amazon/dataprepper/server/DataPrepperServerTest.java

https://github.com/opendistro-for-elasticsearch/Data-Prepper/issues/201
- Adding DataPrepperServer class to construct a server with the handlers we need to serve APIs for the DataPrepper
- Adding PrometheusMetricsHandler to serve the scrape of the Prometheus registry

Adding DataPrepperServer and PrometheusMetricsHandler

---

data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

https://github.com/opendistro-for-elasticsearch/Data-Prepper/issues/214
- Updating armeria WebClient.execute() call to call join(), so that the future is run
- Updating test to assert a 415 (media type unsupported) error, which is what is expected
- Removing extra test for http, since this is no longer needed

Updating OtelTraceSourceTests

---

data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/HashRing.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerClientPool.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarder.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/DiscoveryMode.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProviderFactory.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/StaticPeerListProvider.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/HashRingTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerClientPoolTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderConfigTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProviderFactoryTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/StaticPeerListProviderTest.java

*Issue #, if available:* #200 
* Defined PeerListProvider interface and static implementation (w/ factory)
* Factored out PeerClientPool for managing GRPC clients
* Starting to invert dependencies in PeerForwarder class so it's not responsible for building/managing its dependencies
Manually tested with 2 Prepper instances and the following entry-pipeline:
```
entry-pipeline:
delay: "100"
source:
otel_trace_source:
processor:
- peer_forwarder:
discovery_mode: "static"
data_prepper_ips:
- "data-prepper"
- "data-prepper2"
sink:
- pipeline:
name: "raw-pipeline"
- pipeline:
name: "service-map-pipeline"
```

#200: Added PeerListProvider interface and static implementation.

---

data-prepper-core/integrationTest.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java

https://github.com/opendistro-for-elasticsearch/Data-Prepper/issues/201
- Starting a DataPrepperServer when instantiating DataPrepper instance
- Exposing metrics port on docker container for integ test
- Manually tested getting metrics with integration test
- Actually verifying metrics in the integ test will be cumbersome, TODO later
- Taking in the server port as configuration will be handled in a later task, as this will require a little bit of a refactor in how we parse configuration

Starting data prepper server when initializing the data prepper instance

---

data-prepper-core/integrationTest.gradle
data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndServiceMapTest.java
data-prepper-core/src/integrationTest/resources/pipeline.yml

- Refactors some setup functions in endToEndServiceMapTest
- Add an additional instance of data-prepper in gradle docker
- Included peerforwarder in the data-prepper pipeline.yml
Note: not sure how to handle create arbitrary number of data prepper containers in gradle task w/o hardcoding. Since it is not blocking, will leave it to future if necessary.

TST: including peer forwarder in e2e servicemap test

---

build-resources.gradle
data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/ListPipelinesHandler.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/PrometheusMetricsHandler.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/ShutdownHandler.java
data-prepper-core/src/test/java/com/amazon/dataprepper/server/DataPrepperServerTest.java
data-prepper-plugins/service-map-stateful/build.gradle

https://github.com/opendistro-for-elasticsearch/Data-Prepper/issues/233
- Adding HttpHandlers for List and Shutdown APIs
- Accepting pointer to DataPrepper into the DataPrepperServer constructor
- Adding tests for the 2 new handlers
Note: The PipelineListing object will contain more information about the pipeline (such as isRunning) in the future, when that information is available from the pipeline.

Adding "/list" and "/shutdown" APIs to DataPrepperServer

---

THIRD-PARTY
examples/adot/docker-compose.yml
examples/jaeger-hotrod/docker-compose.yml
examples/kibana-trace-analytics/Dockerfile
examples/trace-analytics-sample-app/docker-compose.yml
examples/zipkin-sleuth-webmvc-example/docker-compose.yml

* Including the THIRD-PARTY attributions. This has only the dependecy for version 0.7.0-alpha. Need to have a separate story on how we plan to do this in the future. 
* Updating the examples to 1.12.0 release of ODFE and latest data-prepper docker. 

Include THIRD-PARTY attributions. Update examples with docker images.

---

data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/ShutdownHandler.java

* A small fix to the Data Prepper server shutdown logic. By doing the server shutdown before the response prints an unwanted exception of stream channel closed. 
* Added log statements to print start and shutdown of Data Prepper Server.
Note: When I included the ElasticsearchSink the shutdown doesn't happen gracefully this is because the ElasticSearchSink uses highlevel client and this needs to closed. 
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-getting-started-initialization.html 
*Testing*
** Logs **
```
~/open-source/Data-Prepper/release/archives/macos/build/distributions/data-prepper-v0.7.0-alpha-macos-x64 master* ⇡
❯ ./data-prepper-tar-install.sh /Users/kowshikn/open-source/Data-Prepper/examples/file_sink.yml …
```

Fix Data Prepper Server shutdown flow.

---

data-prepper-plugins/elasticsearch/build.gradle

- Remove unnecessary elasticsearch core library dependency in ES sink
Note: For now javax.ws.rs is used for HttpMethod constants such as GET, PUT, DELETE, HEAD. So I will keep it there.

CLN: elasticsearch dependency

---

data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSink.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSinkIT.java

Following the latest change in data-prepper-api, moved logic from stop() to shutdown()

MAINT: implement shutdown API and remove stop method in ElasticsearchSink

---

data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/test/java/com/amazon/dataprepper/metrics/PluginMetricsTest.java
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepperExecute.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/DataPrepperConfiguration.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/Log4JConfiguration.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/test/java/com/amazon/dataprepper/DataPrepperTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/TestDataProvider.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/DataPrepperConfigurationTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/Log4JConfigurationTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/server/DataPrepperServerTest.java
data-prepper-core/src/test/resources/invalid_data_prepper_config.yml
data-prepper-core/src/test/resources/invalid_port_data_prepper_config.yml
data-prepper-core/src/test/resources/valid_data_prepper_config.yml
data-prepper-core/src/test/resources/valid_data_prepper_config_default_log4j.yml
data-prepper-core/src/test/resources/valid_data_prepper_some_default_config.yml
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/source/RandomStringSource.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/RandomStringSourceTests.java

https://github.com/opendistro-for-elasticsearch/data-prepper/issues/202
- Supporting DataPrepperConfiguration for server port and Log4j properties
- Adding RandomStringSource for easier local testing 
Note: The cleanest way of setting Log4j properties at runtime is to reconfigure Log4j with a complete set of Properties. Overriding a single property is not easily supported (it is possible with log level, but not log file). Because of this, I had to add the whole set of properties that we want to set and not change to the Log4JConfiguration class

Adding and supporting DataPrepperConfiguration

---

data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/HashRing.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProviderFactory.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/HashRingTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/DiscoveryMode.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/DnsPeerListProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/PeerListProviderFactoryTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/discovery/StaticPeerListProviderTest.java

*Issue #, if available:* #239
Small PR to increase coverage of classes in the peer-forwarder project. I'm leaving the actual PeerForwarder class alone as it is undergoing development. 
New coverage values are 69%/56% (lines/branches). It's interesting to note that the PeerForwarder class shows 0% coverage, probably something with the way it's instrumented. Will fix in a future PR.

Increased unit test coverage for peer-forwader plugin package.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/test/java/com/amazon/dataprepper/metrics/PluginMetricsTest.java
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarder.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/processor/peerforwarder/PeerForwarderTest.java

#200 
- ~Added forwardRequestErrorCounter as a custom metric in PeerForwarder~
- ~Added a test case to cover the metric~
This PR 
- Add an overload of gauge API in PluginMetrics
- Introduced peerforwarder custom metrics as in the checklist
- Refined test cases on PeerForwarder and verified metrics values

ADD: custom metrics in peer-forwarder

---

data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/BulkRetryStrategy.java
data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSink.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/BulkRetryStrategyTests.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSinkIT.java

#253 
- Added meters to produce desired custom metrics as listed in #253 .
- Modified BulkRetryStrategyTests to cover metrics.
- Modified ElasticsearchSinkIT to cover metrics.

ENH: custom metrics in ElasticsearchSink

---

data-prepper-plugins/service-map-stateful/build.gradle
data-prepper-plugins/service-map-stateful/src/test/java/com/amazon/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java

https://github.com/opendistro-for-elasticsearch/data-prepper/issues/239
- Adding 90% code coverage target for service map stateful processor
- There are catch blocks in this code that are not testable currently, because they would require us injecting a factory for creating the processor state objects. That work only buys us more testability, so for now it seems that it is not high priority

Adding code coverage target for service map stateful processor

---

build.gradle
data-prepper-plugins/peer-forwarder/build.gradle

#239 
- Remove redundant jacocoTestReport in coreProjects config
- Enforce jacocoTestReport to depend on tests in all subprojects
- Enforced 90% coverage on peerforwarder.
Note: right now peerforwarder is covered up to 94%. The missing lines and branches concentrate in `Peerforwarder.isAddressDefinedLocally(String)` which is a private method and includes some adhoc exception related to java.net. Pushing for testability on that API might require refactoring.

Clean up jacoco in the overall build and enforce minimum coverage on peerforwarder

---

build-resources.gradle
data-prepper-api/src/main/java/com/amazon/dataprepper/prepper/state/PrepperState.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/state/PrepperStateTest.java
data-prepper-plugins/lmdb-prepper-state/src/main/java/com/amazon/dataprepper/plugins/prepper/state/LmdbPrepperState.java
data-prepper-plugins/mapdb-prepper-state/src/main/java/com/amazon/dataprepper/plugins/prepper/state/MapDbPrepperState.java
data-prepper-plugins/mapdb-prepper-state/src/test/java/com/amazon/dataprepper/plugins/prepper/state/MapDbPrepperStateTest.java
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java
data-prepper-plugins/service-map-stateful/src/test/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepperTest.java

#201 
- Adds sizeInBytes function to MapDbPrepper state to retrieve file size in bytes
- Adds sizeInBytes function to interface PrepperState
- Test case to check sizeInBytes
TODO:

First pass of adding metrics to Service Map Stateful Prepper

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/CheckpointState.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/CheckpointStateTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/ProcessWorker.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/buffer/BlockingBuffer.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/BlockingBufferTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/TestBuffer.java

#216 
This PR 
1. Draft the initial model of CheckpointStates that takes in the number of records to be checked.
2. Add checkpoint API into Buffer interface and fix relevant places
3. Invoke the checkpoint API in the processWorker.
4. Modified BlockingBuffer to add number of inflight records as state variable.
5. Implemented checkpoint API in BlockingBuffer to keep track of inflight data
6. Modified doWrite API in BlockingBuffer to control inflight data below buffer capacity by introducing lock with explicit condition variable.
Note: Test cases that cover BlockingBuffer are synchronized. I expect async features to be at least partially covered by e2e tests. But if necessary, we should try to device those async tests.
By submitting this …

ENH: initial checkpoint model and API

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/ProcessWorker.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/buffer/BlockingBuffer.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/BlockingBufferTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/TestBuffer.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/FileSourceTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/source/StdInSourceTests.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

#216 
This PR
- Modifies Buffer interface read to return both collection of records and CheckpointState
- Same as above in AbstractBuffer
- Made corresponding implementation change in BlockingBuffer
- Fix ProcessWorker invocation of buffer.read
- Fix all affected test cases

ENH: buffer read returns CheckpointState

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

Adding initial CFN template. Tested against a public AWS ES instance with an IAM role access policy. Still need to test w/ VPC, and potentially update the Data Prepper config default values.

Added initial EC2 CFN template.

---

examples/aws/README.md
examples/aws/jaeger-hotrod-on-ec2/README.md
examples/aws/jaeger-hotrod-on-ec2/setup-jaeger-hotrod.sh

We want to allow users to quickly setup a sample Jaeger app to emit trace data for Data Prepper to consume so they can try out the new trace analytics plugin.
* Added an /examples/aws directory for AWS-specific content
* Added a single bash script to install necessary components for running the HotROD app via docker-compose
* Users will run `sh setup-jaeger-hotrod.sh` to stand up a working application
* I'll add readme's to the new aws and jaeger directories in a follow-up. 
The alternative to a setup script is giving the user a series of steps like:
1. Install Docker
1. Install Docker Compose
1. Clone this repo
1. Navigate to /examples/aws/<something>
1. Run `docker-compose up -d`
This setup script is extremely focused and hides the technical details, but I …

Added Jaeger HotROD on EC2 setup script.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/MetricNames.java
data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/PluginMetrics.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/CheckpointState.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-api/src/test/java/com/amazon/dataprepper/metrics/PluginMetricsTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/CheckpointStateTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/buffer/BlockingBuffer.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/BlockingBufferTests.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

This PR introduces the following metrics in AbstractBuffer
- recordsInflightCounter
- recordsProcessedCounter (checkpointed records)
- checkpointTimer
and removes the recordsReadCounter as now it breaks down into recordsInflightCount + recordsProcessedCount

ENH: metrics in AbstractBuffer

---

deployment/aws/ec2/data-prepper-ec2-deployment-cfn.yaml

*Issue #, if available:* #304
* Added parameters for buffer size, buffer batch size, and worker count
* Let me know if the default values should be changed
Did not add JVM heap parameters - those are set in `data-prepper-tar-install-x64.sh` and aren't configurable with just a CFN template update. Of course we can change that file but we'll have to update the release artifacts too. Figure we can make the heap configurable after this launch.

Added pipeline and buffer parameters to the CFN template.

---

examples/dev/trace-analytics-sample-app/resources/data-prepper-wait-for-odfe-and-start.sh
shared-config/log4j.properties

1. Fixed typo in log4j properties file (`plugin` to `plugins`)
2. Reduced logging threshold from ERROR to WARN to not hide Armeria warnings
* I didn't see an increase in log noise, but if it does become too noisy then we can just elevate `com.linecorp.armeria.client` instead
3. Fixed the dev example app not passing in the log4j file on startup

Fixed minor typo in log4j properties file.

---

data-prepper-core/src/integrationTest/resources/pipeline.yml
data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java
data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfigTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderTest.java
deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml
docs/readme/trace_overview.md
examples/dev/k8s/data-prepper.yaml
examples/dev/trace-analytics-sample-app/resources/trace_analytics_no_ssl.yml
examples/trace_analytics_no_ssl.yml

*Issue #, if available:* #308
* Switched the `DEFAULT_SSL` boolean from `false` to `true` in OTelTraceSource and PeerForwarder
* Added explicit `falses` to existing unit tests to maintain functionality

308: Enabling TLS by default in OTelTraceSource and PeerForwarder.

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/DataPrepperServer.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/PrometheusMetricsHandler.java
data-prepper-core/src/test/java/com/amazon/dataprepper/DataPrepperTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/server/DataPrepperServerTest.java
data-prepper-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
examples/dev/trace-analytics-sample-app/prometheus/prometheus.yaml

#329 
This PR 
(1) Introduced JVM and system metrics into DataPrepper class by a PrometheusMeterRegistry singleton separate from `Metrics.globalRegistry`. 
(2) Added /metrics/sys API path into the DataPrepperServer to query the above metrics.
(3) Added test cases for data prepper and server.

ENH: introduce JVM and sys metrics in DataPrepper

---

data-prepper-plugins/elasticsearch/README.md
data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ConnectionConfiguration.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ConnectionConfigurationTests.java

#341 
This PR tackles option 1 in #341 . As discussed offline with @kowshikn , for now we do not need ARN support at the data-prepper level. The data-prepper built from this PR has been run on the VPC EC2 instance that connects with AES configured with custom endpoint.

ENH: support custom AES endpoint with SSL certificate file

---

.github/dependabot.yml
build-resources.gradle
build.gradle
data-prepper-api/build.gradle
data-prepper-core/build.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/blocking-buffer/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/lmdb-prepper-state/build.gradle
data-prepper-plugins/mapdb-prepper-state/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle

* Removed version map (except for opentelemetry_proto for now)
* Enabled dependabot on remaining packages
* Included a lengthy comment as to why we're not using the latest micrometer release. 
* Will open an issue on the micrometer repo asking why the maven artifact are showing as targeting Java 15 even though build.gradle specifies Java 8
* Edit: PR to micrometer: https://github.com/micrometer-metrics/micrometer/pull/2471
* Will also close/ignore dependabot upgrades for micrometer if they are opened until this is figured out

Enabling dependabot on more directories, removing most of versionMap.

---

.github/dependabot.yml

* Noticed we weren't getting any pull requests for projects in the _plugins_ directory, so will attempt to fix by listing them all out.
* Also changing the schedule to "weekly" because we can trigger on-demand scans with https://github.com/opendistro-for-elasticsearch/data-prepper/network/updates

dependabot.yml: explicitly listing out plugin directories.

---

build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/Log4JConfiguration.java
data-prepper-core/src/test/java/com/amazon/dataprepper/DataPrepperTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/DataPrepperConfigurationTests.java
data-prepper-core/src/test/java/com/amazon/dataprepper/parser/model/Log4JConfigurationTests.java
data-prepper-plugins/elasticsearch/build.gradle
examples/dev/trace-analytics-sample-app/docker-compose.yml
shared-config/log4j2.properties

* Switching the logging backend from log4j to log4j2
* Had to include a new log4j2.properties file as the upgrade isn't 100% backwards compatible
I also had a question as to if we should keep the log4j runtime configuration stuff via DP config, as it seems we're already passing in a log4j.properties file as part of the startup command - figured we can discuss that here.
I'll go back and clean up some of the docs around the old log4j stuff once this is merged. 

Switching to log4j2.

---

.github/pull_request_template.md

Adding DCO to PR requests by default. This is coming from an internal request. I've seen other ODFE repos either do this or require commits to be signed off ([example](https://github.com/opendistro-for-elasticsearch/kibana-reports/pull/336/files)).
Figured we'd go this route for now, can always move the DCO to the CONTIBUTING.md file and require commits to be signed. We'd probably want a bot to enforce commit signing as well.

Adding DCO to PR template.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/annotations/SingleThread.java
data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/PipelineTests.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/PrepperFactory.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/PrepperFactoryTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/TestPrepper.java
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java

#320 
This PR 
(1) Introduces a @SingleThread annotation for Prepper plugin to allow confinement of prepper instance to a single ProcessWorker.
(2) Modified `PrepperFactory` to return appropriately based on the @SingleThread.
(3) Modified `Pipeline` and `PipelineParser` correspondingly.
(4) Refactored some relevant test cases

ENH: allow confine Prepper plugin instance to thread

---

data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/PipelineConnector.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/PipelineConnectorTest.java

*Issue #, if available:* #443
* Changing PipelineConnector to continuously retry writing to the buffer, instead of crashing if MAX_INT has somehow elapsed.
-----
permitted to submit under a different license), as …

#443: PipelineConnector no longer throws exception on timeout.

---

data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Still seeing a failing test during GitHub builds, difficult to reproduce. Adding a print statement to hopefully help debug.
Example failure: https://github.com/opendistro-for-elasticsearch/data-prepper/pull/496/checks?check_run_id=2321506008
-----
by me, under the same open …

Added debug code around the failing testBufferFull() test.

---

.github/pull_request_template.md
CONTRIBUTING.md

* Updating DCO guidelines to require commits to be signed.
* See [OpenSearch repo](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) as a guide.
-----
work with modifications, whether created in whole or in …

Updated CONTRIBUTING docs to include commit signing for DCO.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/Buffer.java
data-prepper-api/src/main/java/com/amazon/dataprepper/model/prepper/Prepper.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/buffer/AbstractBufferTest.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/prepper/AbstractPrepperTest.java
data-prepper-core/integrationTest.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/PipelineParser.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/Pipeline.java
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/ProcessWorker.java
data-prepper-core/src/test/java/com/amazon/dataprepper/pipeline/PipelineTests.java
data-prepper-plugins/blocking-buffer/src/main/java/com/amazon/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java
data-prepper-plugins/blocking-buffer/src/test/java/com/amazon/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/NoOpPrepper.java
data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/prepper/StringPrepper.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/buffer/TestBuffer.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/StringPrepperTests.java
data-prepper-plugins/common/src/test/java/com/amazon/dataprepper/plugins/prepper/TestPrepper.java
data-prepper-plugins/mapdb-prepper-state/src/main/java/com/amazon/dataprepper/plugins/prepper/state/MapDbPrepperState.java
data-prepper-plugins/otel-trace-group-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltracegroup/OTelTraceGroupPrepper.java
data-prepper-plugins/otel-trace-group-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/oteltracegroup/OTelTraceGroupPrepperTests.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepper.java
data-prepper-plugins/otel-trace-raw-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepperTest.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarder.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderTest.java
data-prepper-plugins/service-map-stateful/src/main/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepper.java
data-prepper-plugins/service-map-stateful/src/test/java/com/amazon/dataprepper/plugins/prepper/ServiceMapStatefulPrepperTest.java
shared-config/log4j2.properties

*Issue #, if available:* #476
Need to ensure pipelines and components are shut down in a graceful manner to prevent data loss (specifically within stateful components). Added 2 new APIs to the Prepper interface: `prepareForShutdown()` and `isReadyForShutdown()`. High level flow:
1. Shutdown API is called on the server
2. `shutdown()` is called on each Pipeline. Pipelines are sorted in a topological order such that shutdown occurs starting upstream and proceeding downstream.
3. Within each pipeline:
1. The source is stopped to prevent new data from entering
2. Preppers are notified of the shutdown via `prepareForShutdown()`. This allows them time to clear state by flushing records
* There's still an improvement here to be made when dealing with long chains of …

Revised shutdown behavior to limit data loss.

---

data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceGrpcServiceTest.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

*Issue #, if available:* #221
* Removing flaky test in favor of assertions on mocked objects instead of an actual server
-----

Small refactor of OTelSource unit tests to remove flaky test.

---

data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/discovery/PeerListProviderFactory.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/discovery/PeerListProviderFactoryTest.java

#437 
-----
This PR adds validation before initializing a peer provider. 
Note: I have verified that invalid endpoint in addn-hosts of dnsmasq, e.g.
```
10.10.1.2 prepper-cluster
10_10.1.3 prepper-cluster
```
will not be ack by endpointGroup:
```
2021-04-20T16:33:17,543 [main] INFO  com.amazon.dataprepper.plugins.prepper.peerforwarder.discovery.DnsPeerListProvider - Found endpoints: [Endpoint{prepper-cluster, ipAddr=10.10.1.2, weight=1000}]
```
while valid endpoint:
```
10.10.1.2 prepper-cluster
10.10.1.3 prepper-cluster
```
will still be Ack:
```
2021-04-20T16:30:23,453 [main] INFO  com.amazon.dataprepper.plugins.prepper.peerforwarder.discovery.DnsPeerListProvider - Found endpoints: [Endpoint{prepper-cluster, ipAddr=10.10.1.2, …
```

ENH: peer forwarder domain or ip validator

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/configuration/PluginSetting.java
data-prepper-api/src/test/java/com/amazon/dataprepper/model/configuration/PluginSettingsTests.java

This change is to allow the yaml property values for boolean, integer, and long values to be passed in as strings. This is supported for elements in the data-prepper config and some of the elements in the pipeline config. Nulls values are also now supported. Custom elements in source and sinks do not support this. It is not supported because the parsing of those configurations is done with custom code while the data-prepper config supports it because it uses json property binding via Jackson libraries. This changes brings more consistency throughout the config files.
String values were previously not supported but now they are:
```
entry-pipeline: 
source: 
otel_trace_source:  
health_check_service: "false"  
port: "8080"  
```
Null values were previously not supported but now they are: …

String attributes for boolean, long, int for pipeline yaml config

---

.github/workflows/data-prepper-trace-analytics-e2e-tests.yml
.github/workflows/gradle.yml
.github/workflows/opensearch-sink-odfe-before-1_13_0-integration-tests.yml
.github/workflows/opensearch-sink-odfe-since-1_13_0-integration-tests.yml

Noticed duplicate test runs were being started when PRs are opened/code pushed ([example](https://github.com/opendistro-for-elasticsearch/data-prepper/pull/560)). This is an attempt to fix it.
-----

Updated workflows to potentially stop duplicate actions from firing.

---

data-prepper-core/build.gradle
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/server/CloudWatchMeterRegistryProvider.java
data-prepper-core/src/main/resources/cloudwatch.properties
data-prepper-core/src/test/java/com/amazon/dataprepper/server/CloudWatchMeterRegistryProviderTest.java
data-prepper-core/src/test/resources/cloudwatch_test.properties

* Adds CloudWatchRegistry
_Please note that the registry is not currently hooked to data prepper, the current meter registry will still be Prometheus which is already hooked. This PR only adds the CloudWatchRegistry enabling customers who wish to use Cloudwatch to replace Prometheus with CloudWatch_
*Testing after updating the global registry*
Have tested on my dev account and below is the screenshot 
-----

Add CloudWatchMeterRegistry

---

deployment-template/ec2/data-prepper-ec2-deployment-cfn.yaml

#313 
-----
This PR adds failure signal into CFN by looking up exception in the log. Did not figure out a way to report the error message back

MAINT: report back failure if exception found in data-prepper.log

---

data-prepper-plugins/otel-trace-source/README.md
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java

* Adds feasibility to configure unframed requests via data prepper pipeline configuration for otel_trace_source
*Testing*
* Verified on local
```
$ curl -H 'Content-Type: application/json; charset=utf-8' -d '{"resourceSpans":[{"instrumentationLibrarySpans":[{"spans":[{"spanId":"AAAAAAAAAAM=","name":"test-span"}]}]}]}'  localhost:21890/opentelemetry.proto.collector.trace.v1.TraceService/Export
related log for data prepper
2021-05-17T14:00:28,108 [entry-pipeline-prepper-worker-1-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker -  entry-pipeline Worker: Processing 1 records from buffer
2021-05-17T14:00:28,208 [service-map-pipeline-prepper-worker-3-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker - …
```

Add capability to configure unframed requets from otel trace source configuration

---

data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/DataPrepperConfiguration.java
data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSink.java
data-prepper-plugins/elasticsearch/src/main/resources/otel-v1-apm-service-map-index-template.json
data-prepper-plugins/elasticsearch/src/main/resources/otel-v1-apm-span-index-template.json
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSinkIT.java
data-prepper-plugins/elasticsearch/src/test/resources/test-index-template-v2.json

*Issue #, if available:* #569
* Added logic in ES Sink to check version of index templates before attempting to POST them into the cluster.
* Added an integ test which asserts index templates are not overwritten by prior versions
* Multiple whitespace/formatting fixes from IDE auto-formatter. Suggest viewing this PR with whitespace changes hidden.
-----

Added version to index template schemas.

---

data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSink.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ElasticsearchSinkIT.java

#491 
-----
This PR:
(1) Captures invalid raw-span index alias caused by existing index under the same name from misoperation on ES backend.
(2) make sure REST client gets cleaned up if ElasticsearchSink starts failed to prevent thread leakage.

Bug Fixes: capture invalid index alias exception and display instructive msg

---

data-prepper-benchmarks/mapdb-benchmarks/build.gradle
data-prepper-benchmarks/service-map-stateful-benchmarks/build.gradle
data-prepper-core/build.gradle
data-prepper-core/integrationTest.gradle
data-prepper-plugins/blocking-buffer/build.gradle
data-prepper-plugins/build.gradle
data-prepper-plugins/common/build.gradle
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/mapdb-prepper-state/build.gradle
data-prepper-plugins/otel-trace-group-prepper/build.gradle
data-prepper-plugins/otel-trace-raw-prepper/build.gradle
data-prepper-plugins/otel-trace-source/build.gradle
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/service-map-stateful/build.gradle
examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
release/archives/build.gradle
release/build.gradle
research/zipkin-elastic-to-otel/build.gradle

*Issue #, if available:* N/A
I fixed some Gradle deprecation warnings. I also noticed that some projects are intended to be libraries, though they were not building that way. I change a few of them to get their transitive dependencies working with `api` dependencies.
I don't think we will be able to support Gradle 7 and JDK 16 yet because of dependencies on OpenSearch/ElasticSearch. Regardless, I hope these changes get us ready for such an update.
-----
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opendistro-for-elasticsearch/data-prepper/blob/main/CONTRIBUTING.m …

Fixed Gradle deprecation warnings.

---

docs/schemas/trace-analytics/otel-v1-apm-service-map-index-template.md
docs/schemas/trace-analytics/otel-v1-apm-span-index-template.md
docs/schemas/trace-analytics/readme.md

*Issue #, if available:* #586
* Added schema docs
* Added versioning guidelines
-----

Added trace-analytics schema documentation.

---

data-prepper-plugins/elasticsearch/build.gradle

Issue #666 
As described in the issue, the AWS STS library is required at runtime to support IRSA.  If the maintainers are happy to package the dependency with data-prepper, this could ease adoption as I had to debug the app to understand why this wasn't working.
I've matched the version of the AWS STS library to the AWS Core library included in this plugin.   (Elsewhere in this project I see v2 of the AWS SDK used)
-----

Fixes #666 by including AWS STS library required for IRSA in EKS

---

data-prepper-api/src/main/java/com/amazon/dataprepper/metrics/MetricNames.java
data-prepper-core/src/main/java/com/amazon/dataprepper/DataPrepper.java
data-prepper-core/src/main/java/com/amazon/dataprepper/parser/model/MetricRegistryType.java

* Adds dimension to MeterRegistry - this way the metrics will have a default dimension to drill into.
* Enables to use environment variable `DATAPREPPER_SERVICE_NAME` if we execute datapreppers in containerized frameworks
-----

Metric dimension

---

.github/dependabot.yml

* Changing Dependabot scans from weekly to monthly to cut down on maintenance tasks
-----

Changing Dependabot scans from weekly to monthly.

---

data-prepper-api/src/main/java/com/amazon/dataprepper/model/buffer/AbstractBuffer.java
data-prepper-core/src/integrationTest/resources/raw-span-e2e-pipeline-latest-release.yml
data-prepper-core/src/integrationTest/resources/raw-span-e2e-pipeline.yml
data-prepper-core/src/main/java/com/amazon/dataprepper/pipeline/Pipeline.java
data-prepper-plugins/otel-trace-raw-prepper/README.md
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepper.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OtelTraceRawPrepperConfig.java
data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/model/OTelProtoHelper.java
data-prepper-plugins/otel-trace-raw-prepper/src/test/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepperTest.java
data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java

* Changed Prepper logic to no longer use a DelayQueue to allow child spans to arrive after the root span. This is instead handled by the traceID cache. 
* Changed Sink thread count per pipeline to equal the number of "workers" 
-----

Refactor of OTelTraceRawPrepper to improve performance.

---

data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/peer-forwarder/build.gradle
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPool.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProviderConfig.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProviderFactory.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/acm/ACMCertificateProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/file/FileCertificateProvider.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/model/Certificate.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/s3/S3CertificateProvider.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPoolTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfigTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/CertificateProviderFactoryTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/acm/ACMCertificateProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/file/FileCertificateProviderTest.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/s3/S3CertificateProviderTest.java

Changes include:
* Added support to build the trust manager by abstracting how the certificates are read. The certificate can be local file system location, AWS ACM ARN or AWS S3 location.
* Added unit test to support above case.
Signed-off-by: Dinu John <86094133+dinujoh@users.noreply.github.com>
-----

Add support to read certificate from ACM and S3 for peer forwarder

---

data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java

Signed-off-by: David Venable <dlv@amazon.com>
*Issue #, if available:* 
None
While reviewing the code, I noticed that the `OTelTraceSource` always registers a `HealthGrpcService`. We have a boolean flag which appears to be how we should determine whether to include it. I made this change to only conditionally add the service. Additionally, I added unit tests for both scenarios.
-----

Only register the Health gRPC service when it is configured to be used.

---

data-prepper-plugins/elasticsearch/README.md
data-prepper-plugins/elasticsearch/build.gradle
data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ConnectionConfiguration.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ConnectionConfigurationTests.java

*Issue #731:* 
Add support of STS assume role option.
-----

Add support of STS assume role.

---

data-prepper-plugins/elasticsearch/README.md
data-prepper-plugins/elasticsearch/src/main/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ConnectionConfiguration.java
data-prepper-plugins/elasticsearch/src/test/java/com/amazon/dataprepper/plugins/sink/elasticsearch/ConnectionConfigurationTests.java

* The roleSessionName has length constraint max of 64 characters.
* Removing the pipelineName as the length was exceeding 64 characters.
Signed-off-by: Dinu John <86094133+dinujoh@users.noreply.github.com>
-----

Update roleSessionName to be less that 64 character

---

data-prepper-plugins/peer-forwarder/README.md
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPool.java
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfig.java
data-prepper-plugins/peer-forwarder/src/test/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerClientPoolTest.java

* Adding a config key to Peer Forwarder to allow the target port to be configurable.
-----

Allowing PeerForwarder port to be configurable.

---

data-prepper-core/integrationTest.gradle
data-prepper-core/src/integrationTest/resources/raw-span-e2e-pipeline-latest-release.yml
data-prepper-core/src/integrationTest/resources/service-map-e2e-pipeline.yml
data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/PeerForwarderConfig.java

* Found previous vnode count (10) did not distribute load very evenly while load testing. Increasing the vnode count.
**Note:** This is a dangerous change in that clusters running old and new versions of Data Prepper will have inconsistent hash values due to the vnode change. This is why I had to slightly adjust the hostnames in the integration tests, so that the hash values would coincidentally line up between old and new DP versions (only in the test env). 
The alternative is to allow users to configure the vnode count and default it to 10, however in the long term I think providing yet another knob to configure is worse for usability.
-----
By submitting this pull …

Updated hash ring vnode count to more evenly distribute load.

---

THIRD-PARTY
build.gradle
data-prepper-plugins/elasticsearch/build.gradle

Signed-off-by: David Powers <ddpowers@amazon.com>
Upgraded log4j to 2.15.0
-----

Upgrade log4j to 2.15.0

---

build.gradle

Ensures CVE-2021-44228 is applied everywhere.
Uses a Gradle constraint to ensure log4j-core is 2.15.0 minimum.
-----

Log4j 2.15 constraint

---

THIRD-PARTY
build.gradle
data-prepper-plugins/elasticsearch/build.gradle

*Issue #, if available:* N/A
Updated to log4j-2.16.0.
Log4j 2.16.0 fixes [CVE-2021-45046](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046).
-----

Updated to log4j-2.16.0
